# Generated by Django 4.0.3 on 2022-04-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userextension_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextension',
            name='link',
            field=models.URLField(default='', null=True),
        ),
    ]
