# Generated by Django 4.0.3 on 2022-04-11 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculadoraInteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=30)),
                ('ahorro_mensual', models.DecimalField(decimal_places=2, max_digits=30)),
                ('interes', models.DecimalField(decimal_places=2, max_digits=30)),
                ('acumulado_con_interes', models.DecimalField(decimal_places=2, max_digits=30)),
                ('acumulado_sin_interes', models.DecimalField(decimal_places=2, max_digits=30)),
                ('año', models.IntegerField(max_length=4)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
