# Generated by Django 4.0.3 on 2022-04-18 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('capital_inicial', models.DecimalField(decimal_places=2, max_digits=50)),
                ('capital_adicional', models.DecimalField(decimal_places=2, max_digits=50)),
                ('interes', models.DecimalField(decimal_places=2, max_digits=50)),
                ('años', models.PositiveIntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CapitalTiempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('capital', models.DecimalField(decimal_places=2, max_digits=50)),
                ('calc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitaltiempo', to='calculator.calculadora')),
            ],
        ),
    ]
