# Generated by Django 4.0.3 on 2022-04-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculadora',
            name='años',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='capitaltiempo',
            name='year',
            field=models.IntegerField(),
        ),
    ]
