# Generated by Django 4.0.3 on 2022-04-11 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_alter_calculadorainteres_año'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculadorainteres',
            name='acumulado_con_interes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='calculadorainteres',
            name='acumulado_sin_interes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='calculadorainteres',
            name='año',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
